"""empty message

Revision ID: 364d73e39938
Revises: eebedeaa4bf4
Create Date: 2020-04-24 20:35:16.413381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364d73e39938'
down_revision = 'eebedeaa4bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'image_link')
    op.add_column('Show', sa.Column('start_time', sa.Date(), nullable=False))
    op.drop_column('Show', 'date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date_time', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'start_time')
    op.add_column('Artist', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
